In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


# One Dimensional Array

In [21]:
import numpy as np 

In [2]:
myList = [1, 2, 3, 4, 5]
arr = np.array(myList)

In [3]:
arr 

array([1, 2, 3, 4, 5])

In [4]:
arr2 = np.arange(1, 101)
arr2 

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [5]:
arr3 = np.arange(1, 101, 2)
arr3 

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [6]:
arr2.shape 

(100,)

In [18]:
arr3.shape

(50,)

In [8]:
arr3[5]

11

# Two Dimensional Array

In [9]:
myNestedList = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
myNestedList[1][1]

5

In [12]:
myNestedArray = np.array(myNestedList)
myNestedArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
myNestedArray[1][1]

5

In [16]:
firstList = [1, 2, 3]
secondList = [4, 5, 6]

firstArr = np.array([firstList, secondList])

In [17]:
firstArr

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
firstArr.shape 

(2, 3)

# Creating Arrays From Functions

In [23]:
np.zeros(50)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.zeros((10, 10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [27]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
np.full(10, 20)

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [31]:
np.full(shape=(3, 5), fill_value=8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [33]:
np.linspace(1, 20, 10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [34]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Reshaping Arrays

In [35]:
fArray = np.arange(1, 26)
fArray 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [36]:
fArray.shape

(25,)

In [39]:
sArray = fArray.reshape(5, 5)
sArray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [40]:
sArray.shape

(5, 5)

In [41]:
sampleArr = np.array([1, 2, 3, 4, 5, 6])
sampleArr

array([1, 2, 3, 4, 5, 6])

In [42]:
sampleArr.shape

(6,)

In [44]:
sampleArr2 = sampleArr.reshape(2, -1) 
sampleArr2

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
sampleArr2.shape

(2, 3)

# Indexing 

In [46]:
arr2 

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [47]:
arr2[10:20]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [48]:
myNestedArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
myNestedArray[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
myNestedArray[:2, 1:]

array([[2, 3],
       [5, 6]])

In [54]:
#Fancy Indexing 

arr2[[5, 6, 20, 35, 1]]

array([ 6,  7, 21, 36,  2])

# Random Arrays

In [3]:
#Random values between 0 and 1

np.random.rand(10)

array([0.36050592, 0.31865281, 0.71293005, 0.48546561, 0.62930384,
       0.75713979, 0.65351327, 0.70202256, 0.14144133, 0.84201439])

In [5]:
np.random.rand(5, 5)

array([[0.9183755 , 0.5787075 , 0.25908835, 0.21861921, 0.22485152],
       [0.6390745 , 0.05613925, 0.71049555, 0.14313363, 0.60855079],
       [0.84674871, 0.23710306, 0.56100092, 0.72829347, 0.7985627 ],
       [0.18851597, 0.9373716 , 0.93262254, 0.43077294, 0.43633986],
       [0.2701064 , 0.19359481, 0.42690991, 0.88401454, 0.86787454]])

In [7]:
#Random values from the standard normal distribution

np.random.randn(2, 4)

array([[ 0.76554449, -0.65031321,  0.50646808, -0.10926849],
       [ 1.06841308, -0.01426195,  0.06839039, -1.27201866]])

In [6]:
np.random.binomial(9, 0.1, 20000)

array([1, 2, 1, ..., 0, 1, 1])

In [ ]:
intArray = np.random.randint(1, 100, (50,5))
intArray

# Aggregate Functions

In [12]:
intArray.min() 

1

In [13]:
intArray.max()

99

In [14]:
intArray.sum()

13468

In [15]:
intArray.mean()

53.872

In [16]:
intArray[0].sum()

209

In [18]:
intArray.dtype

dtype('int64')

In [19]:
intArray.argmin()

24

In [20]:
intArray.argmax()

9

# Sorting Arrays

In [22]:
unsortedArr = np.array([5, 20, 100, 4, 35])
unsortedArr

array([  5,  20, 100,   4,  35])

In [24]:
unsortedArr.sort()
unsortedArr

array([  4,   5,  20,  35, 100])

In [25]:
unsortedArr[::-1].sort()

In [26]:
unsortedArr

array([100,  35,  20,   5,   4])

In [27]:
type(unsortedArr)

numpy.ndarray

In [28]:
uArr = np.array([5, 20, 100, 4, 35])
uArr 

array([  5,  20, 100,   4,  35])

In [29]:
sorted(uArr)

[4, 5, 20, 35, 100]

In [30]:
sorted(uArr, reverse=True)

[100, 35, 20, 5, 4]

# Broadcasting

In [31]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
arr[:5] = 10

In [33]:
arr

array([10, 10, 10, 10, 10,  6,  7,  8,  9, 10])

In [34]:
arr[:] = 100

In [35]:
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

# Slicing vs Copying

In [36]:
arr2 = np.arange(1, 11)
arr2 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
sliceArr = arr2[1:6]
sliceArr

array([2, 3, 4, 5, 6])

In [38]:
sliceArr[:] = 1000
sliceArr

array([1000, 1000, 1000, 1000, 1000])

In [39]:
arr2

array([   1, 1000, 1000, 1000, 1000, 1000,    7,    8,    9,   10])

In [40]:
copyArr = arr2.copy()
copyArr

array([   1, 1000, 1000, 1000, 1000, 1000,    7,    8,    9,   10])

In [41]:
copyArr[5] = 20

In [42]:
copyArr

array([   1, 1000, 1000, 1000, 1000,   20,    7,    8,    9,   10])

In [43]:
arr2

array([   1, 1000, 1000, 1000, 1000, 1000,    7,    8,    9,   10])

# Boolean Arrays

In [44]:
qArr = np.arange(1, 11)
qArr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
qArr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [46]:
qArr%2==0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [47]:
qArr[qArr%2==0]

array([ 2,  4,  6,  8, 10])

# Array Arithmetic

In [56]:
a = np.array([5, 10, 15, 20])
b = np.array([10])

In [57]:
a+b

array([15, 20, 25, 30])

In [58]:
a-b

array([-5,  0,  5, 10])

In [59]:
a*b

array([ 50, 100, 150, 200])

In [53]:
a/b

array([0.5, 0.5, 0.5, 0.5])

# Universal Array Functions

In [60]:
np.sqrt(a)

array([2.23606798, 3.16227766, 3.87298335, 4.47213595])

In [67]:
np.cbrt(a)

array([1.70997595, 2.15443469, 2.46621207, 2.71441762])

In [61]:
np.exp(a)

array([1.48413159e+02, 2.20264658e+04, 3.26901737e+06, 4.85165195e+08])

In [62]:
np.sin(a)

array([-0.95892427, -0.54402111,  0.65028784,  0.91294525])

In [63]:
np.cos(a)

array([ 0.28366219, -0.83907153, -0.75968791,  0.40808206])

In [64]:
np.tan(a)

array([-3.38051501,  0.64836083, -0.8559934 ,  2.23716094])

In [65]:
np.log(a)

array([1.60943791, 2.30258509, 2.7080502 , 2.99573227])

In [66]:
np.abs(a)

array([ 5, 10, 15, 20])